ARG PACKAGE_REGISTRY
ARG PR_TAG
FROM $PACKAGE_REGISTRY/php:%%VERSION_TAG%%$PR_TAG

%%GENERATED_WARNING%%

RUN curl -sL https://phar.phpunit.de/phpunit-%%PHPUNIT_VERSION%%.phar > /usr/local/bin/phpunit && chmod +x /usr/local/bin/phpunit

WORKDIR /var/www

COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT [ "entrypoint.sh" ]

CMD /usr/local/bin/phpunit
