FROM garypendergast/wordpress-develop-php:5.2-fpm

##########################################################################
#
# WARNING: This file was generated by update.php. Do not edit it directly.
#
#

# install wp-cli dependences
RUN set -ex; \
	\
	apt-get update; \
	\
	apt-get install -y --no-install-recommends \
		less \
		mysql-client \
	;

RUN set -ex; \
	\
	curl -L -o /usr/local/bin/wp https://github.com/wp-cli/wp-cli/releases/download/v1.5.1/wp-cli-1.5.1.phar; \
	\
	chmod +x /usr/local/bin/wp; \
	\
	wp --allow-root --version;

WORKDIR /var/www

ENTRYPOINT [ "/usr/local/bin/wp", "--allow-root" ]

CMD [ "shell" ]
