FROM devilbox/php-fpm-5.3:latest

##########################################################################
#
# WARNING: This file was generated by update.php. Do not edit it directly.
#
#



COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]

CMD [ "php-fpm" ]
