FROM %%BASE_NAME%%

WORKDIR /var/www

%%GENERATED_WARNING%%

ENV COMPOSER_ALLOW_SUPERUSER 1
ENV COMPOSER_HOME /tmp

%%INSTALL_EXTENSIONS%%

COPY entrypoint.sh /entrypoint.sh
COPY common.sh /common.sh
COPY php-fpm.conf /usr/local/etc/php-fpm.d/zz-wordpress.conf

RUN chmod +x /entrypoint.sh && \
    chmod +x /common.sh && \
    groupadd -g 1000 -r wp_php && \
    useradd -u 1000 -s /bin/bash -g wp_php wp_php

ENTRYPOINT [ "/entrypoint.sh" ]

CMD [ "php-fpm" ]
