ARG PHP_BASE_IMAGE
ARG PR_TAG
FROM $PHP_BASE_IMAGE:%%VERSION_TAG%%$PR_TAG

%%GENERATED_WARNING%%

RUN curl -sL https://phar.phpunit.de/phpunit-%%PHPUNIT_VERSION%%.phar > /usr/local/bin/phpunit && chmod +x /usr/local/bin/phpunit

WORKDIR /var/www

COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]

CMD /usr/local/bin/phpunit
