name: Build Docker Images

on:
  push:
    branches: master
  pull_request:

env:
  global:
    - DOCKER_USERNAME: garypendergast
    - GITHUB_USERNAME: pento
    - DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - PR_TAG: ${{ github.repository_owner }}
    - PACKAGE_REGISTRY_HOST: ghcr.io
    - PACKAGE_REGISTRY: ghcr.io/wordpress/wpdev-docker-images

jobs:

  build-php-images:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '8.0', '7.4', '7.3', '7.2', '7.1', '7.0', '5.6.20' ]
        os: [ ubuntu-latest ]
    env:
      - PHP_VERSION: ${{ matrix.php }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name:
        if: ${{ github.event == 'push' }}
        run: |
          echo "PACKAGE_REGISTRY_HOST=" >> $GITHUB_ENV
          echo "PACKAGR_REGISTRY=wordpressdevelop" >> $GITHUB_ENV

      - name: Build Docker images
        run: docker build --build-arg PACKAGE_REGISTRY=${{ env.PACKAGE_REGISTRY }} --build-arg PR_TAG=${{ env.PR_TAG }} -t $PACKAGE_REGISTRY/php:${{ env.PHP_VERSION }}-fpm$PR_TAG images/${{ env.PHP_VERSION }}/php

      - name: Log Docker images
        run: docker images

  build-phpunit-images:
    runs-on: ubuntu-latest
    needs: build-php-images
    strategy:
      matrix:
        phpunit: [ '5.2', '5.3', '5.4', '5.5', '5.6.20' ]
        os: [ ubuntu-latest ]
    env:
      - PHPUNIT_VERSION: ${{ matrix.phpunit }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name:
        if: ${{ github.event == 'push' }}
        run: |
          echo "PACKAGE_REGISTRY_HOST=" >> $GITHUB_ENV
          echo "PACKAGR_REGISTRY=wordpressdevelop" >> $GITHUB_ENV

      - name: Build Docker images
        run: docker build --build-arg PACKAGE_REGISTRY=${{ env.PACKAGE_REGISTRY }} --build-arg PR_TAG=${{ env.PR_TAG }} -t $PACKAGE_REGISTRY/php:${{ env.PHPUNIT_VERSION }}-fpm$PR_TAG images/${{ env.PHPUNIT_VERSION }}/phpunit

      - name: Log Docker images
        run: docker images

  build-cli-images:
    runs-on: ubuntu-latest
    needs: build-php-images
    strategy:
      matrix:
        php: [ '8.0', '7.4', '7.3', '7.2', '7.1', '7.0', '5.6.20' ]
        os: [ ubuntu-latest ]
    env:
      - PHP_VERSION: ${{ matrix.php }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name:
        if: ${{ github.event == 'push' }}
        run: |
          echo "PACKAGE_REGISTRY_HOST=" >> $GITHUB_ENV
          echo "PACKAGR_REGISTRY=wordpressdevelop" >> $GITHUB_ENV

      - name: Build Docker images
        run: docker build --build-arg PACKAGE_REGISTRY=${{ env.PACKAGE_REGISTRY }} --build-arg PR_TAG=${{ env.PR_TAG }} -t $PACKAGE_REGISTRY/php:${{ env.PHP_VERSION }}-fpm$PR_TAG images/${{ env.PHP_VERSION }}/cli

      - name: Log Docker images
        run: docker images

