name: Lint GitHub Actions workflows
on:
  workflow_call:

permissions: {}

jobs:
  # Runs the actionlint GitHub Action workflow file linter.
  #
  # This helps guard against common mistakes including strong type checking for expressions (${{ }}), security checks,
  # `run:` script checking, glob syntax validation, and more.
  #
  # See https://github.com/rhysd/actionlint.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Runs actionlint.
  actionlint:
    name: Run actionlint
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}

      - name: Run actionlint
        uses: docker://rhysd/actionlint:1.7.7
        with:
          args: "-color -verbose"

  # Runs the Zizmor workflow file scanner.
  #
  # Zizmor is a static analysis tool for GitHub Actions that can find many common security issues.
  #
  # See https://github.com/zizmorcore/zizmor.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Runs Zizmor.
  # - Uploads the results to GitHub Code Scanning.
  zizmor:
    name: Zizmor
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Run zizmor
        run: uvx zizmor@1.25.0 --format sarif . > results.sarif
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@9e0d7b8d25671d64c341c19c0152d693099fb5ba # v4.35.5
        with:
          sarif_file: results.sarif
          category: zizmor
